# Generated by Django 3.2 on 2021-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.RemoveField(
            model_name='queue',
            name='key',
        ),
        migrations.AddField(
            model_name='queue',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
