# Generated by Django 3.2 on 2021-04-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
        ('queueApp', '0005_alter_qrcode_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
