# Generated by Django 3.2 on 2021-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0008_queue_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='priority',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
