# Generated by Django 3.2 on 2021-04-09 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0002_auto_20210409_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='qr_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queueApp.qrcode'),
        ),
    ]
