# Generated by Django 3.2 on 2021-04-09 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0003_queue_qr_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
