# Generated by Django 3.2 on 2021-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0004_qrcode_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
